global:
  scrape_interval: 15s  # Интервал, с которым Prometheus будет собирать метрики

scrape_configs:
  - job_name: 'orchestra_api'
    static_configs:
      - targets: ['server:8080']  # Адрес твоего API-сервиса
