/*
Orchestra API

Микросервис API для \"Клуба друзей оркестра\". **Все пользователи считаются равными**, а доступ из внешнего мира осуществляется через Telegram-бот.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MembersPost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MembersPost201Response{}

// MembersPost201Response struct for MembersPost201Response
type MembersPost201Response struct {
	Id *string `json:"id,omitempty"`
}

// NewMembersPost201Response instantiates a new MembersPost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMembersPost201Response() *MembersPost201Response {
	this := MembersPost201Response{}
	return &this
}

// NewMembersPost201ResponseWithDefaults instantiates a new MembersPost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMembersPost201ResponseWithDefaults() *MembersPost201Response {
	this := MembersPost201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MembersPost201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MembersPost201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MembersPost201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MembersPost201Response) SetId(v string) {
	o.Id = &v
}

func (o MembersPost201Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MembersPost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableMembersPost201Response struct {
	value *MembersPost201Response
	isSet bool
}

func (v NullableMembersPost201Response) Get() *MembersPost201Response {
	return v.value
}

func (v *NullableMembersPost201Response) Set(val *MembersPost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableMembersPost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableMembersPost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMembersPost201Response(val *MembersPost201Response) *NullableMembersPost201Response {
	return &NullableMembersPost201Response{value: val, isSet: true}
}

func (v NullableMembersPost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMembersPost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
