/*
Orchestra API

Микросервис API для \"Клуба друзей оркестра\". **Все пользователи считаются равными**, а доступ из внешнего мира осуществляется через Telegram-бот.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateMemberStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMemberStatusRequest{}

// UpdateMemberStatusRequest struct for UpdateMemberStatusRequest
type UpdateMemberStatusRequest struct {
	Status string `json:"status"`
}

type _UpdateMemberStatusRequest UpdateMemberStatusRequest

// NewUpdateMemberStatusRequest instantiates a new UpdateMemberStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMemberStatusRequest(status string) *UpdateMemberStatusRequest {
	this := UpdateMemberStatusRequest{}
	this.Status = status
	return &this
}

// NewUpdateMemberStatusRequestWithDefaults instantiates a new UpdateMemberStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMemberStatusRequestWithDefaults() *UpdateMemberStatusRequest {
	this := UpdateMemberStatusRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateMemberStatusRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateMemberStatusRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateMemberStatusRequest) SetStatus(v string) {
	o.Status = v
}

func (o UpdateMemberStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMemberStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateMemberStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMemberStatusRequest := _UpdateMemberStatusRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMemberStatusRequest)

	if err != nil {
		return err
	}

	*o = UpdateMemberStatusRequest(varUpdateMemberStatusRequest)

	return err
}

type NullableUpdateMemberStatusRequest struct {
	value *UpdateMemberStatusRequest
	isSet bool
}

func (v NullableUpdateMemberStatusRequest) Get() *UpdateMemberStatusRequest {
	return v.value
}

func (v *NullableUpdateMemberStatusRequest) Set(val *UpdateMemberStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMemberStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMemberStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMemberStatusRequest(val *UpdateMemberStatusRequest) *NullableUpdateMemberStatusRequest {
	return &NullableUpdateMemberStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateMemberStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMemberStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
