/*
Orchestra API

Микросервис API для \"Клуба друзей оркестра\". **Все пользователи считаются равными**, а доступ из внешнего мира осуществляется через Telegram-бот.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateMemberProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMemberProfileRequest{}

// UpdateMemberProfileRequest struct for UpdateMemberProfileRequest
type UpdateMemberProfileRequest struct {
	FullName string `json:"full_name"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

type _UpdateMemberProfileRequest UpdateMemberProfileRequest

// NewUpdateMemberProfileRequest instantiates a new UpdateMemberProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMemberProfileRequest(fullName string, email string, phone string) *UpdateMemberProfileRequest {
	this := UpdateMemberProfileRequest{}
	this.FullName = fullName
	this.Email = email
	this.Phone = phone
	return &this
}

// NewUpdateMemberProfileRequestWithDefaults instantiates a new UpdateMemberProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMemberProfileRequestWithDefaults() *UpdateMemberProfileRequest {
	this := UpdateMemberProfileRequest{}
	return &this
}

// GetFullName returns the FullName field value
func (o *UpdateMemberProfileRequest) GetFullName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value
// and a boolean to check if the value has been set.
func (o *UpdateMemberProfileRequest) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FullName, true
}

// SetFullName sets field value
func (o *UpdateMemberProfileRequest) SetFullName(v string) {
	o.FullName = v
}

// GetEmail returns the Email field value
func (o *UpdateMemberProfileRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UpdateMemberProfileRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UpdateMemberProfileRequest) SetEmail(v string) {
	o.Email = v
}

// GetPhone returns the Phone field value
func (o *UpdateMemberProfileRequest) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *UpdateMemberProfileRequest) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *UpdateMemberProfileRequest) SetPhone(v string) {
	o.Phone = v
}

func (o UpdateMemberProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMemberProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["full_name"] = o.FullName
	toSerialize["email"] = o.Email
	toSerialize["phone"] = o.Phone
	return toSerialize, nil
}

func (o *UpdateMemberProfileRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"full_name",
		"email",
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMemberProfileRequest := _UpdateMemberProfileRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMemberProfileRequest)

	if err != nil {
		return err
	}

	*o = UpdateMemberProfileRequest(varUpdateMemberProfileRequest)

	return err
}

type NullableUpdateMemberProfileRequest struct {
	value *UpdateMemberProfileRequest
	isSet bool
}

func (v NullableUpdateMemberProfileRequest) Get() *UpdateMemberProfileRequest {
	return v.value
}

func (v *NullableUpdateMemberProfileRequest) Set(val *UpdateMemberProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMemberProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMemberProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMemberProfileRequest(val *UpdateMemberProfileRequest) *NullableUpdateMemberProfileRequest {
	return &NullableUpdateMemberProfileRequest{value: val, isSet: true}
}

func (v NullableUpdateMemberProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMemberProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
