/*
Orchestra API

Микросервис API для \"Клуба друзей оркестра\". **Все пользователи считаются равными**, а доступ из внешнего мира осуществляется через Telegram-бот.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EventsEventIdRegistrationGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventsEventIdRegistrationGet200Response{}

// EventsEventIdRegistrationGet200Response struct for EventsEventIdRegistrationGet200Response
type EventsEventIdRegistrationGet200Response struct {
	// Статус регистрации
	Status *string `json:"status,omitempty"`
}

// NewEventsEventIdRegistrationGet200Response instantiates a new EventsEventIdRegistrationGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventsEventIdRegistrationGet200Response() *EventsEventIdRegistrationGet200Response {
	this := EventsEventIdRegistrationGet200Response{}
	return &this
}

// NewEventsEventIdRegistrationGet200ResponseWithDefaults instantiates a new EventsEventIdRegistrationGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventsEventIdRegistrationGet200ResponseWithDefaults() *EventsEventIdRegistrationGet200Response {
	this := EventsEventIdRegistrationGet200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EventsEventIdRegistrationGet200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventsEventIdRegistrationGet200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EventsEventIdRegistrationGet200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *EventsEventIdRegistrationGet200Response) SetStatus(v string) {
	o.Status = &v
}

func (o EventsEventIdRegistrationGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventsEventIdRegistrationGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableEventsEventIdRegistrationGet200Response struct {
	value *EventsEventIdRegistrationGet200Response
	isSet bool
}

func (v NullableEventsEventIdRegistrationGet200Response) Get() *EventsEventIdRegistrationGet200Response {
	return v.value
}

func (v *NullableEventsEventIdRegistrationGet200Response) Set(val *EventsEventIdRegistrationGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEventsEventIdRegistrationGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEventsEventIdRegistrationGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventsEventIdRegistrationGet200Response(val *EventsEventIdRegistrationGet200Response) *NullableEventsEventIdRegistrationGet200Response {
	return &NullableEventsEventIdRegistrationGet200Response{value: val, isSet: true}
}

func (v NullableEventsEventIdRegistrationGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventsEventIdRegistrationGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
