package service

import "errors"

var (
	ErrEventNotFound           = errors.New("event not found")
	ErrEventFull               = errors.New("event full")
	ErrRegNotFound             = errors.New("registration not found")
	ErrRegAlreadyExists        = errors.New("registration already exists")
	ErrFailedToAdd             = errors.New("failed to add event")
	ErrFailedToDelete          = errors.New("failed to delete event")
	ErrFailedToGet             = errors.New("failed to get event")
	ErrFailedToGetUpcoming     = errors.New("failed to list events")
	ErrFailedToGetAvailable    = errors.New("failed to get available events")
	ErrFailedToGetRegistered   = errors.New("failed to get registered event")
	ErrFailedToGetEvents       = errors.New("failed to get events")
	ErrFailedToUpdate          = errors.New("failed to update event")
	ErrMemberNotApproved       = errors.New("member is not approved")
	ErrMemberNotFound          = errors.New("member not found")
	ErrFailedToAddMember       = errors.New("failed to add member")
	ErrFailedToGetMember       = errors.New("failed to get member")
	ErrFailedToGetMembers      = errors.New("failed to get members")
	ErrFailedToDeleteMember    = errors.New("failed to delete member")
	ErrFailedToUpdateMember    = errors.New("failed to update member")
	ErrFailedToUpdateMemStatus = errors.New("failed to update member status")
	ErrRegistrationFailed      = errors.New("failed to register")
	ErrCancellationFailed      = errors.New("failed to cancel registration")
	ErrStatusCheckFailed       = errors.New("failed to check registration status")
	ErrFailedToSaveMeta        = errors.New("failed to save metadata")
	ErrMetaNotFound            = errors.New("meta object not found")
	ErrInfoNotFound            = errors.New("orchestra info not found")
	ErrUnknownStatus           = errors.New("unknown status")
	ErrEmailDuplicate          = errors.New("email already exists")
	ErrPhoneDuplicate          = errors.New("phone number already exists")
	ErrInvalidEmail            = errors.New("invalid email format")
	ErrInvalidPhone            = errors.New("invalid phone number format")
)
